### ISSUE TITLE
Convert biomes to minecraft-data

### ISSUE THREAD

**Issue by rom1504** [SpockBotMC/SpockBot#177]
I think [biomes.py](https://github.com/SpockBotMC/SpockBot/blob/master/spockbot/mcdata/biomes.py) should be fairly easy to convert (see the data there [biomes.json](https://github.com/PrismarineJS/minecraft-data/blob/1.8/enums/biomes.json) ) and doing that conversion will probably help to know how to convert [blocks.py](https://github.com/SpockBotMC/SpockBot/blob/master/spockbot/mcdata/blocks.py) ( #123 ) which has a similar structure.

Should the same structure remain (using metaclasses or something like that ?) or would a dict work ?

**Comment by Gjum** [comment]
will probably be a list or dict of namedtuples
