### ISSUE TITLE
[question] Using a Proxy

### ISSUE THREAD

**Issue by ThePixelPony** [SpockBotMC/SpockBot#196]
How could one create bots using remote proxies?

**Comment by nickelpro** [comment]
This question needs some clarification. What exactly are you trying to do?

**Comment by rom1504** [comment]
I bet something like  https://github.com/PrismarineJS/node-minecraft-protocol/issues/185 , an http/socks proxy, not Minecraft one

**Comment by nickelpro** [comment]
Socks is trivial to add but I don't really feel like adding it to mainline. If that's a usecase you need to support all you need to do is create a new socket for Spock to connect with for example using https://github.com/Anorov/PySocks .

Spock is explicitly friendly about swapping out core plugins for this reason. If you need a Minecraft proxy, they're a dime a dozen, just pick one. You can build one with Spock in under an hour if you're familiar with the Minecraft protocol.

But ya, I don't really like adding dependencies without a very good reason.

**Comment by ThePixelPony** [comment]
Ah, I see. Thank you - problem is solved. Apologies for not replying - I haven't logged into Github for days.
