### ISSUE TITLE
Error when opening custom item menu

### ISSUE THREAD

**Issue by DefinitlyEvil** [SpockBotMC/SpockBot#208]
```
File "D:\Programs\Python35\lib\site-packages\spockbot-0.1.3-py3.5.egg\spockbot\plugins\helpers\inventory.py", line 170, in handle_open_window
KeyError: 'minecraft:container'
```

PS: Just produced a fix (PR #209)

**Comment by Gjum** [comment]
Thanks for te PR. On what server did you see that inv type?

**Comment by DefinitlyEvil** [comment]
A minecraft server network with a item menu to join sub-servers.

**Comment by nickelpro** [comment]
This bug will be fixed when minecraft-data merges https://github.com/PrismarineJS/minecraft-data/pull/87

**Comment by nickelpro** [comment]
Going to call this fixed unless there are further reports
