### ISSUE TITLE
[ERROR]: AUTH: Session start error, calling kill

### ISSUE THREAD

**Issue by fredyvilla** [SpockBotMC/SpockBot#212]
It seems that the Auth module broke after commit: 5263efc5bc86a1d06e16cb0e57ca8cc8cac599c0 

Steps to reproduce:

python examples/basic/example.py

The MC server.properties file was tested with online_mode=true and online_mode=false.

Spock is not establishing a connecting to the server at all. No entries in the mc log.

**Comment by nickelpro** [comment]
Can't reproduce, you sure your credentials are correct?

**Comment by saucecode** [comment]
Did anyone figure this one out? I'm getting the same problem to a localhost server of version 1.8.8.

**Comment by nickelpro** [comment]
You need to turn off online-mode if you just want local connections without authentication, which is unrelated to this issue anyaay
