### ISSUE TITLE
Problem with python3 setup.py install

### ISSUE THREAD

**Issue by SpikeThatMike** [SpockBotMC/SpockBot#233]
When i try to do python3 setup.py install in the cmd, i get a error and i dont know how to fix this

running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-23824.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again

**Comment by Gjum** [comment]
try either: `python3 setup.py install --user` or use a virtualenv, or try running the command as admin

**Comment by SpikeThatMike** [comment]
Ive done this using that command line, but when i run the example it still says no module named spockbot
