### ISSUE TITLE
Bedrock Compatible?

### ISSUE THREAD

**Issue by LastedApple3** [SpockBotMC/SpockBot#234]
I intend to use this, but I am only capable of using Bedrock servers, and I have no access to any of these to write test programs. I wish to know whether this works with Bedrock servers, and if it isn't then I would like to request that a future modification makes it so it is.

**Comment by nickelpro** [comment]
SpockBot hasn't been maintained in many years, and unfortunately it was never Bedrock compatible, sorry :(
