### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by mrnickzh** [SpockBotMC/SpockBot#235]
yield inv.async.click_slot(ingr_slot)
              ^
SyntaxError: invalid syntax

Im litteraly dont know how to avoid it

**Comment by Gjum** [comment]
This project was made before Python adopted `async/await` and the corresponding keywords; some ways around this include using an older Python version without the `async` keyword or renaming the module to some other word that's not reserved.

**Comment by mrnickzh** [comment]
> This project was made before Python adopted `async/await` and the corresponding keywords; some ways around this include using an older Python version without the `async` keyword or renaming the module to some other word that's not reserved.
thanks, i fix it, but have another problem
