### ISSUE TITLE
Incorrect Player Positions - Coordinates, Yaw & Pitch

### ISSUE THREAD

**Issue by ThePixelPony** [SpockBotMC/SpockBot#44]
I believe that there is an error with the logging of player positions. I haven't tested any other entities but it certainly looks like the case with players. I have tried to collect as much information as possible for you.

My logging code is shown below.
>def onTick(self,_,__): #Only one player online (apart from the bot)
>		for eid in self.entities.players:
>			p = self.entities.players[eid]
>			logger.info(str(p))

The printed results is shown below. At first, the first of these is printed every tick but then it switches to the second result.
>{'yaw': 12, 'current_item': 137, 'eid': 221, 'pitch': 22, 'y': 3200, 'x': -1786, 'z': -55769, 'metadata': [(18, (2, 0)), (17, (3, 0.0)), (16, (0, 0)), (10, (0, 127)), (9, (0, 0)), (8, (0, 0)), (7, (2, 0)), (6, (3, 20.0)), (4, (0, 0)), (3, (0, 0)), (2, (4, u'')), (1, (1, 300)), (0, (0, 0))]}

>{'on_ground': True, 'yaw': 12, 'current_item': 137, 'eid': 221, 'pitch': 22, 'y': 3200, 'x': -1786, 'z': -55769, 'metadata': [(18, (2, 0)), (17, (3, 0.0)), (16, (0, 0)), (10, (0, 127)), (9, (0, 0)), (8, (0, 0)), (7, (2, 0)), (6, (3, 20.0)), (4, (0, 0)), (3, (0, 0)), (2, (4, u'')), (1, (1, 300)), (0, (0, 0))]}

Below is an image with the exact position etc of the player (with 'eid' 221).
<img src="http://www.dropbox.com/s/z1v4o6pc83sccud/Screenshot%202015-02-10%2019.45.49.png?dl=1" />

I have checked that I was logging the correct player by making them hold a command block (137); the bot player was not holding one. The player that I logged was perfectly still whilst the logs were being collected.

**Comment by zezadas** [comment]
this will be fixed soon, I guess...

**Comment by nickelpro** [comment]
Discussed in PR: https://github.com/SpockBotMC/SpockBot/pull/42

I have the fix for FP encoder/decoder written. I'll get it pushed in a couple hours when I get back to my computer

**Comment by nickelpro** [comment]
Should be fixed in: 5a1bf57fb8978f1587c74548e4be9d238591a6c8

**Comment by ThePixelPony** [comment]
I have just tested this and can confirm that it is working flawlessly! :+1:
