### ISSUE TITLE
inventory.py not Python 2.7.6 compatible

### ISSUE THREAD

**Issue by LucidBlue** [SpockBotMC/SpockBot#63]
`super().__init__()` cannot be called this way in Python 2.7. Calling the super class by name, e.g. `Slot.__init__` seems to do the trick, but this may not be a correct way to handle it.

**Comment by Gjum** [comment]
When writing the inventory code, I did not try it for 2.7, sorry. The crafting module also has to be changed for 2.7 compatibility, when I get around to do that, I will also make the inventory code compatible.

I have seen a fix somewhere by using something like `super(ClassName, self).__init__()`, so you could use that until I (or someone else) start working on it again.
